
#net.minecraft.storagebox.mod_StorageBox
[configuration]
	#String: "minecraft:stone%1=>minecraft:granite,minecraft:stone%2=>minecraft:smooth_granite,minecraft:stone%3=>minecraft:diorite,minecraft:stone%4=>minecraft:smooth_diorite,minecraft:stone%5=>minecraft:andesite,minecraft:stone%6=>minecraft:smooth_andesite,minecraft:log%1=>minecraft:spruce_log,minecraft:log%2=>minecraft:birch_log,minecraft:log%3=>minecraft:jungle_log,minecraft:log2%0=>minecraft:acacia_log,minecraft:log2%1=>minecraft:dark_oak_log"
	#chage old ID(ResourceLocation%damage) to new ID.
	ItemID_ReadAs = "minecraft:stone%1=>minecraft:granite,minecraft:stone%2=>minecraft:smooth_granite,minecraft:stone%3=>minecraft:diorite,minecraft:stone%4=>minecraft:smooth_diorite,minecraft:stone%5=>minecraft:andesite,minecraft:stone%6=>minecraft:smooth_andesite,minecraft:log%1=>minecraft:spruce_log,minecraft:log%2=>minecraft:birch_log,minecraft:log%3=>minecraft:jungle_log,minecraft:log2%0=>minecraft:acacia_log,minecraft:log2%1=>minecraft:dark_oak_log"
	#String: "KEY_COLON"
	keyCode = "KEY_COLON"
	#Boolean: true
	#Enable/Disable auto collect in a chest.
	autoCollectInChest = true
	#Boolean: false
	AddName = false
	#Integer: 0
	Position = 0
	#Integer: 16777215
	Color = 16777215
	#Boolean: false
	AddCount = false
	#Boolean: true
	AutoCollect = true
	#Boolean: false
	#find StorageBox in ender chest item in plyaer's inventory.
	exploreEnderChest = false

